/*
 * ViewAppDetails.java
 *
 * Created on 12 October, 2009, 11:42 PM
 */

package factory;
import ctracker.*;
import java.sql.*;
/**
 *
 * @author  Vidhoon
 */
public class ViewAppDetails extends javax.swing.JFrame {

    /** Creates new form ViewAppDetails */
    public ViewAppDetails() {
        initComponents();
           connector ob=new connector();
            
     try
        {
           Connection my=ob.connect();
        
        
           Statement s=my.createStatement();
          
           ResultSet rs = s.executeQuery("select appid from  appinfo");
           
           while(rs.next())
           {
               applist.addItem(rs.getString("appid"));
           }
     }
     catch(Exception e)
     {
         System.out.println(e);
     }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        applist = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        det = new javax.swing.JTextArea();
        getdetails = new javax.swing.JButton();
        ana = new javax.swing.JButton();
        ud = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APP ID");

        det.setColumns(20);
        det.setLineWrap(true);
        det.setRows(5);
        jScrollPane1.setViewportView(det);

        getdetails.setText("Fetch");
        getdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getdetailsMouseClicked(evt);
            }
        });
        getdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getdetailsActionPerformed(evt);
            }
        });

        ana.setText("Add New App");
        ana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anaMouseClicked(evt);
            }
        });

        ud.setText("Update Details");
        ud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                udMouseClicked(evt);
            }
        });

        close.setText("close");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(applist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(getdetails)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(ana)
                .addGap(42, 42, 42)
                .addComponent(ud)
                .addGap(38, 38, 38)
                .addComponent(close)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(applist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(getdetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana)
                    .addComponent(ud)
                    .addComponent(close))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void getdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getdetailsActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_getdetailsActionPerformed

private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
this.setVisible(false);
    // TODO add your handling code here:
}//GEN-LAST:event_closeMouseClicked

private void anaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anaMouseClicked
// TODO add your handling code here:
    ReleaseNewApp ob=new ReleaseNewApp();
    ob.setVisible(true);
    
}//GEN-LAST:event_anaMouseClicked

private void udMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_udMouseClicked
// TODO add your handling code here:
 UpdateAppInfo ob=new UpdateAppInfo();
    ob.setVisible(true);
}//GEN-LAST:event_udMouseClicked

private void getdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getdetailsMouseClicked
// TODO add your handling code here:
    det.setText("");
    String aid,an,ac,ad,aen,ap,ainfo=null;
    
    aid=(String)applist.getSelectedItem();
           connector ob=new connector();
      int a=Integer.parseInt(aid);      
     try
        {
           Connection my=ob.connect();
        
        
           Statement s=my.createStatement();
          
           ResultSet rs = s.executeQuery("select * from  appinfo where appid="+a);
           
           if(rs.next())
           {
            //   applist.addItem(rs.getString("appid"));
               
               an="App Name: "+rs.getString("appname");
               ac="Cost: "+rs.getString("appcost");
               ad="Desc: "+rs.getString("appdesc");
               aen="Enhancements: "+rs.getString("appen");
               ap="Power: "+rs.getString("apppow");
               
               ainfo=an+"\n"+ac+"\n"+ad+"\n"+aen+"\n"+ap+"\n\n" ;
               
               det.setText(ainfo);
               
           }
     }
     catch(Exception e)
     {
         System.out.println(e);
     }
}//GEN-LAST:event_getdetailsMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAppDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ana;
    private javax.swing.JComboBox applist;
    private javax.swing.JButton close;
    private javax.swing.JTextArea det;
    private javax.swing.JButton getdetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ud;
    // End of variables declaration//GEN-END:variables

}
