/*
 * InsideOperator.java
 *
 * Created on 6 October, 2009, 8:21 PM
 */

package ctracker;
import java.sql.*;
/**
 *
 * @author  Vidhoon
 */
public class InsideOperator extends javax.swing.JFrame {

    /** Creates new form InsideOperator */
    public InsideOperator() {
        initComponents();
        chooseappid.removeAllItems();
        cplist.removeAllItems();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        usersearchpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchtext = new javax.swing.JTextField();
        byname = new javax.swing.JRadioButton();
        bypno = new javax.swing.JRadioButton();
        bycaid = new javax.swing.JRadioButton();
        bycid = new javax.swing.JRadioButton();
        scdet = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cdet = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        spdet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pdet = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        chooseappid = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cplist = new javax.swing.JComboBox();
        gcdet = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cpdet = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome");

        usersearchpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Search by");

        searchtext.setColumns(15);
        searchtext.setText("searchtext");
        searchtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtextActionPerformed(evt);
            }
        });

        buttonGroup1.add(byname);
        byname.setText("name");

        buttonGroup1.add(bypno);
        bypno.setText("phone number");

        buttonGroup1.add(bycaid);
        bycaid.setText("c-app-ID");
        bycaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bycaidActionPerformed(evt);
            }
        });

        buttonGroup1.add(bycid);
        bycid.setText("c-ID");

        scdet.setText("Search");
        scdet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scdetMouseClicked(evt);
            }
        });
        scdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scdetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usersearchpanelLayout = new javax.swing.GroupLayout(usersearchpanel);
        usersearchpanel.setLayout(usersearchpanelLayout);
        usersearchpanelLayout.setHorizontalGroup(
            usersearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersearchpanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(searchtext, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(usersearchpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(usersearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersearchpanelLayout.createSequentialGroup()
                        .addComponent(bycid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(scdet)
                        .addGap(26, 26, 26))
                    .addGroup(usersearchpanelLayout.createSequentialGroup()
                        .addGroup(usersearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bypno)
                            .addComponent(byname)
                            .addComponent(bycaid))
                        .addContainerGap(125, Short.MAX_VALUE))))
        );
        usersearchpanelLayout.setVerticalGroup(
            usersearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersearchpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(usersearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(usersearchpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(byname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bypno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bycaid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bycid)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(usersearchpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scdet)
                        .addContainerGap())))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Customer Details");

        cdet.setColumns(20);
        cdet.setRows(5);
        jScrollPane2.setViewportView(cdet);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PRODUCT DETAILS"));

        spdet.setText("Retrive");
        spdet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spdetMouseClicked(evt);
            }
        });
        spdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spdetActionPerformed(evt);
            }
        });

        pdet.setColumns(20);
        pdet.setRows(5);
        jScrollPane1.setViewportView(pdet);

        jLabel6.setText("C App ID");

        chooseappid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(spdet)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(chooseappid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(239, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(spdet))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chooseappid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Complaint Detail");

        cplist.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cplist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cplistActionPerformed(evt);
            }
        });

        gcdet.setText("Retrieve");
        gcdet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gcdetMouseClicked(evt);
            }
        });

        cpdet.setColumns(20);
        cpdet.setRows(5);
        jScrollPane3.setViewportView(cpdet);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addComponent(cplist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gcdet)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cplist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(gcdet)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Pick Call");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Logout");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jButton2.setText("Edit Cus preferences");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Add FAQ");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usersearchpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton2)
                        .addGap(93, 93, 93)
                        .addComponent(jButton1)
                        .addGap(61, 61, 61)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(usersearchpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel5))
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void searchtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_searchtextActionPerformed

private void cplistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cplistActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cplistActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void scdetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scdetMouseClicked
// TODO add your handling code here:
    
    
    
    String stext=searchtext.getText();
    connector ob=new connector();
            
     try
        {
           Connection my=ob.connect();
        
        
           Statement s=my.createStatement();
          
           ResultSet rs = null;
    if(byname.isSelected())
    {
       
           rs=s.executeQuery("select * from cinfo where cname='"+stext+"' order by cname");
          
    }
    else if(bypno.isSelected())
    {
        
          rs=s.executeQuery("select * from cinfo where cphone='"+stext+"' order by cname");
    }
    else if(bycaid.isSelected())
    {
        
           rs=s.executeQuery("select * from cinfo where cappid='"+stext+"' order by cname");
    }
    else if(bycid.isSelected())
    {
        
           rs=s.executeQuery("select * from cinfo where cid='"+stext+"' order by cname");
    }
     
     
    int cap=0;;
    while(rs.next())
    {
        String cinf=null;
        String cname,cid,cappid,cpn,caddr;
       
        
        cname="Cus Name: "+rs.getString("cname");
        cid="Cus ID: "+rs.getString("cid");
        cappid="Cus AppID: "+rs.getString("cappid");
        cpn="Cus PhoneNo: "+rs.getString("cphone");
        caddr="Cus Addr: "+rs.getString("caddr");
        cap=Integer.parseInt(rs.getString("cappid"));
        cinf=cname+"\n"+cid+"\n"+cappid+"\n"+cpn+"\n"+caddr+"\n\n";
        cdet.append(cinf);
        
        chooseappid.addItem(rs.getString("cappid"));
        
        cusid=rs.getInt("cid");
        o.setcid(cusid);
        System.out.println(cap);
        ResultSet rk=s.executeQuery("select * from comp where cappid="+cap); 
        
        while(rk.next())
        {
            cplist.addItem(rk.getString("cpid"));
        }
      
    }
        
     }
     catch(Exception e)
     {
         System.out.println("some error"+e);
     }
    
   
}//GEN-LAST:event_scdetMouseClicked

private void bycaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bycaidActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_bycaidActionPerformed

private void spdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spdetActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_spdetActionPerformed

private void scdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scdetActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_scdetActionPerformed

private void spdetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spdetMouseClicked
// TODO add your handling code here:
    
        String scapid=(String)chooseappid.getSelectedItem();
        
        int capid=Integer.parseInt(scapid);
        o.setcapid(capid);
        
        connector ob=new connector();
            
     try
        {
           Connection my=ob.connect();
        
        
           Statement s=my.createStatement();
          
           ResultSet rs = s.executeQuery("select * from capp where cappid="+capid); 
       
           
           if(rs.next())
           {
           String pinf,dop,aid,mop,wp;
         
           dop="DOP: "+rs.getString("dop");  
           aid="App ID: "+rs.getInt("appid");   
           mop="Pay Mode: "+rs.getString("mop");   
           wp="Warranty: "+rs.getInt("wp");   
           
           pinf=aid+"\n"+dop+"\n"+mop+"\n"+wp+"\n\n";//product info
           
           pdet.append(pinf);
           
           
           }
               // System.out.println(capid);
           ResultSet rp = s.executeQuery("select cpid from comp where cappid="+capid+"");
      
           while(rp.next())
           {
               
                cplist.addItem(rp.getString("cpid"));
           }
     }
     catch(Exception e)
     {
         System.out.println("some error"+e);
     }
}//GEN-LAST:event_spdetMouseClicked

private void gcdetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gcdetMouseClicked
// TODO add your handling code here:
    
    String scpid=(String)cplist.getSelectedItem();
    int cpid=Integer.parseInt(scpid);
    System.out.println(cpid);
    o.setcpid(cpid);
            connector ob=new connector();
            
     try
        {
           Connection my=ob.connect();
        
        
           Statement s=my.createStatement();
          
           ResultSet rs = s.executeQuery("select * from comp where cpid="+cpid);
           
           String cpinf,cpdesc,cpdate,cprem;
           if(rs.next())
           {
           cpdesc="Desc: "+rs.getString("cpdesc");
           cpdate="Date :"+rs.getString("cpdate");
           cprem="Remarks: "+rs.getString("cpremark");
           
           cpinf=cpdesc+"\n"+cpdate+"\n"+cprem+"\n\n";
           
           cpdet.append(cpinf);
           }
     }
     catch(Exception e)
     {
         System.out.println(e);
     }
       

}//GEN-LAST:event_gcdetMouseClicked

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
// TODO add your handling code here:
    
     o.setVisible(true);
    //this.setVisible(false);
   

        
}//GEN-LAST:event_jButton1MouseClicked

private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
// TODO add your handling code here:
    
    this.setVisible(false);
    Login a=new Login();
    a.setVisible(true);
    a.setTitle("Call operator login");
}//GEN-LAST:event_jLabel5MouseClicked

private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
// TODO add your handling code here:
    ChangePrefer a=new ChangePrefer(cusid);
    a.setVisible(true);
    a.setTitle("Customer preferences");
}//GEN-LAST:event_jButton2MouseClicked

private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
// TODO add your handling code here:
    AddFaq obk=new AddFaq();
    obk.setVisible(true);
    obk.setTitle("Add FAQ");
}//GEN-LAST:event_jButton3MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsideOperator().setVisible(true);
            }
        });
    }
private int cusid; 
private CallSession o=new CallSession();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton bycaid;
    private javax.swing.JRadioButton bycid;
    private javax.swing.JRadioButton byname;
    private javax.swing.JRadioButton bypno;
    private javax.swing.JTextArea cdet;
    private javax.swing.JComboBox chooseappid;
    private javax.swing.JTextArea cpdet;
    private javax.swing.JComboBox cplist;
    private javax.swing.JButton gcdet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea pdet;
    private javax.swing.JButton scdet;
    private javax.swing.JTextField searchtext;
    private javax.swing.JButton spdet;
    private javax.swing.JPanel usersearchpanel;
    // End of variables declaration//GEN-END:variables

}
